# yaml-language-server: $schema=../../values-schemas/cloudnative-pg/values.schema.json
replicaCount: 2
tolerations:
  - key: workload-placement
    operator: Equal
    value: restricted
    effect: NoSchedule
config:
  clusterWide: false
image:
  repository: ghcr.io/cloudnative-pg/cloudnative-pg
  tag: 1.30.1@sha256:923c267ec29636db3bee20f993d0ec4973fa22998e1adad37da79e4d32b5bc07
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
monitoring:
  podMonitorEnabled: true
  grafanaDashboard:
    create: true
    namespace: postgresql
    configMapName: cnpg-grafana-dashboard
    labels:
      grafana_dashboard: "1"
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: cloudnative-pg
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: cloudnative-pg
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
