apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    name: in-cluster
    namespace: openbao
  project: default
  sources:
    - repoURL: https://github.com/dmuiX/k3s-on-omv-infra.git
      targetRevision: 25e8fb5ccfd62a6c55ea90a2ebc51f164e7240f2
      path: charts/cluster-config
      helm:
        valueFiles:
          - $values/clusters/omv/values.yml
        parameters:
          - name: component
            value: backups
    - repoURL: https://github.com/dmuiX/k3s-on-omv-live.git
      targetRevision: ce6ad756dd48ef28145f836e6825a65fcafe548f
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: Secret
      namespace: openbao
      jsonPointers:
        - /data
