apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-access-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    name: in-cluster
    namespace: openbao
  project: default
  source:
    repoURL: https://github.com/dmuiX/k3s-on-omv-infra.git
    targetRevision: main
    path: 04-openbao-access-config/workload
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
