apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-access-config
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao-access-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
automountServiceAccountToken: false
