apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  sources:
    - repoURL: https://github.com/dmuiX/k3s-on-omv-infra.git
      targetRevision: ea09c0829860af0ceff9ae21f3d37f0a319b3196
      path: charts/cluster-config
      helm:
        valueFiles:
          - $values/clusters/omv/values.yml
        parameters:
          - name: component
            value: certificates
    - repoURL: https://github.com/dmuiX/k3s-on-omv-live.git
      targetRevision: ce6ad756dd48ef28145f836e6825a65fcafe548f
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: Secret
      name: cloudflare-token
      namespace: cert-manager
      jsonPointers:
        - /data
