apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccounts.yaml
  - rbac.yaml
  - networkpolicy.yaml
  - initial-job.yaml
  - cronjob.yaml
  - issuers.yaml
  - openbao-internal-certificate.yaml
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: openbao-pki-reconciler
configMapGenerator:
  - name: openbao-pki-reconciler
    namespace: openbao
    files:
      - reconcile.py
      - config.json
      - cert-manager-pki-services-sign.hcl=policies/cert-manager-pki-services-sign.hcl
      - cert-manager-pki-clients-sign.hcl=policies/cert-manager-pki-clients-sign.hcl
