apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-internal-tls
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: internal-tls
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: openbao-internal-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - server auth
  dnsNames:
    - openbao-active-tls.openbao.svc
    - openbao-active-tls.openbao.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: openbao-pki-services
