apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-pki-tokenrequests
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: openbao-pki
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames:
      - openbao-pki-services
      - openbao-pki-clients
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-pki-tokenrequests
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: openbao-pki
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openbao-pki-tokenrequests
