apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-pki-reconciler
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao-pki-reconciler
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-pki-services
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: openbao-pki-services
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-pki-clients
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: openbao-pki-clients
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
automountServiceAccountToken: false
