apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-route
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    name: in-cluster
    namespace: openbao
  project: default
  sources:
    - repoURL: https://github.com/dmuiX/k3s-on-omv-infra.git
      targetRevision: 5077f8d9e1257e7dcd54ed68c66f0ccc745b53d6
      path: charts/cluster-config
      helm:
        valueFiles:
          - $values/clusters/omv/values.yml
        parameters:
          - name: component
            value: openbao
    - repoURL: https://github.com/dmuiX/k3s-on-omv-live.git
      targetRevision: ce6ad756dd48ef28145f836e6825a65fcafe548f
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 12
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
