apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: platform-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  namespaceSelector:
    matchNames: [postgresql]
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: platform-postgres
  podMetricsEndpoints:
    - port: exporter
      interval: 30s
      scrapeTimeout: 10s
