apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  minAvailable: 2
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/control-plane: pgo
