apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
      app.kubernetes.io/instance: cloudnative-pg
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: plugin-barman-cloud
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plugin-barman-cloud
      app.kubernetes.io/instance: plugin-barman-cloud
